spring:
  cache:
    type: none
  application:
    name: mod-calendar
  jackson:
    default-property-inclusion: NON_NULL
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_DATABASE:okapi_modules}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.yaml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  banner:
    location: classpath:/banner.txt

management:
  endpoints:
    web:
      base-path: /admin

feign:
  client:
    config:
      default:
        loggerLevel: full

logging:
  level:
    org:
      springframework:
        cache: OFF
      hibernate:
        type: TRACE

server.port: 8080

folio:
  tenant:
    validation:
      enabled: true
  logging:
    request:
      enabled: true
    feign:
      enabled: true
