openapi: 3.0.3
info:
  title: Calendar API
  version: v4.1
servers:
  - url: /
paths:
  /hello:
    $ref: paths/hello.yaml
  /calendar/periods:
    $ref: paths/calendar/periods.yaml
  /calendar/periods/{servicePointId}/period:
    $ref: paths/calendar/periods/servicePointId/period.yaml
  /calendar/periods/{servicePointId}/period/{periodId}:
    $ref: paths/calendar/periods/servicePointId/period/periodId.yaml
